name: Build Constitution

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt dependencies for TeX
        run: sudo apt-get install -y tex-common texlive-extra-utils texlive-fonts-extra texlive-formats-extra texlive latexmk

      - name: Compile LaTeX via latexmk
        run: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf main.tex

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: constitution
          path: main.pdf

      - name: Copy built constitution to web folder
        run: cp main.pdf pages/constitution.pdf

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
