name: Build Constitution

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install apt dependencies for TeX
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: tex-common texlive-extra-utils texlive-fonts-extra texlive-formats-extra texlive latexmk
          version: 1.0

      - name: Compile LaTeX via latexmk
        run: latexmk

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: constitution
          path: main.pdf
